import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Events App Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>

      <main className={styles.main}>

        {data.map((ev) => (
          <a key={ev.id} href={`events/${ev.id}`}>
            <Image width={200} height={100} alt={ev.title} src={ev.image} /> 
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          
          </a>
        ))
        }

      </main>

      <footer className={styles.footer}>
        &copy; 2023 Lennox Charles - An Event App Manager Project
      </footer>
    </>
  )
}

// it will only work like this, if you put it in the function above it won't work
// this function runs before the main page that is rendered and it is rendered on the server
export async function getServerSideProps () {
  const {events_categories} = await import('data/data.json')
 
  return {
    props: {
      data: events_categories,
    }
  }
}